spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: vsV8Po339xySOEBY7Ic8Gx+hpfwARC5MxHvm8HoC9QymrUK7vpU0EUTH9+gj/cBv6S9sTyWgYOGIPBqWI4UTXA==
