spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    hibernate:
      ddl-auto: update


jwt:
  secret: vsV8Po339xySOEBY7Ic8Gx+hpfwARC5MxHvm8HoC9QymrUK7vpU0EUTH9+gj/cBv6S9sTyWgYOGIPBqWI4UTXA==

# 전체 로깅 레벨
#logging:
#  level:
#    root: trace