spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
